### ISSUE TITLE
Create Carla environment suitable for Reinforcement Learning

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/curlad#1]
Create an environment that interacts with CARLA. The environment should have at least three methods:

- **init:** Initialize all variables, sensors, vehicles, configurations...
- **reset:**  Reset the state of the simulation, spawn vehicles...
- **step:** Run one step of the simulation. Receive action as input and then return the next observation and reward.

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira and @vitoruapt,

I just finished the first version of the carla environment. I used a dummy agent (throttle=1) for a simple demonstration:

https://uapt33090-my.sharepoint.com/:v:/g/personal/danielsilveiracoelho_ua_pt/EVx0wFS5caZNpcFGjVABuJ0BEIMoWg9O_E7ginkZzvmbNQ?e=e6fxOj

It stops the episode whenever the vehicle collides, runs a red light, or a stop sign.

Now I'll focus on the configuration files both for the environment (town, weather, number of zombie vehicles, pedestrians, etc.) and for the ego_vehicle (model, sensors, etc.).

**Comment by miguelriemoliveira** [comment]
Hi @DanielCoelho112 ,

it looks good. And you already have different weather, traffic, etc. Great work.

Does it work in sync mode? Can you run it step by step with something like a cvwaitkey(0) on the client's side?

If the criteria to stop an episode is when the car hits or passes a red light, we could end up with episodes with very distinct durations. Would that no be a problem?

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira,

this is already in sync mode:

```python  
    score = 0
    while not done:      
      
        throttle = 1
        steer = 0
        brake = 0
        control = carla.VehicleControl(throttle=throttle, steer=steer, brake=brake)
        
        observation_, reward, done, info = env.step(control)
        score += reward
        
        image = observation_['central_rgb']['data']
        cv2.imshow('central_camera', image)
        cv2.waitKey(1)
        
        print(f'Is the episode over? {Fore.MAGENTA} {done} {Fore.RESET}')
        observation = observation_
        n_steps += 1
```


> If the criteria to stop an episode is when the car hits or passes a red light, we could end up with episodes with very distinct durations. Would that no be a problem?

No, not a problem. It is quite common to have episodes with different length. When the agent is taking actions in a certain episode, it keeps the transitions in an experience replay common to all episodes. So when it is time to update the parameters, we just need to sample a fixed amount of transitions from the experience replay, which contains data from all episodes.

**Comment by DanielCoelho112** [comment]
This is done.
