### ISSUE TITLE
Create episode stats folder

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/curlad#13]
This folder should contain some statistics about each episode in the training.

**Comment by DanielCoelho112** [comment]
Done. This folder contains the following csv:

[episode_stats.csv](https://github.com/DanielCoelho112/curlad/files/9910027/episode_stats.csv)

In addition, it also contains some plots with relevant features, such as the cumulative reward per episode:
![reward](https://user-images.githubusercontent.com/73063947/199239169-a392af10-d28a-4c1d-a3e9-2c361dea1ea4.png)

**Comment by miguelriemoliveira** [comment]
Only negative rewards? Because its the dummy agent?

**Comment by DanielCoelho112** [comment]
> Because its the dummy agent?
Yes. 

Although the fact that the rewards are negative is not a problem. The agent will always try to maximize the rewards in relative terms. Depending on the design of the reward function, -1000 can be a good reward (if the other rewards are below that). 

What I mean is that just by looking at the value of the reward we cannot infer whether this reward is good or not.

**Comment by miguelriemoliveira** [comment]
Right.
